/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/gin-gonic/gin"
	sw "github.com/olgasinepalnikova/avito-task-2025-winter/server/go"
	"log"
	"os"
)

var jwtSecret []byte

func init() {
	secret := os.Getenv("JWT_SECRET")
	if secret == "" {
		log.Fatal("JWT_SECRET environment variable is not set")
	}
	jwtSecret = []byte(secret)
}

func main() {
	api := sw.DefaultAPI{
		DB:       sw.ConnectToDatabase(),
		JWTToken: jwtSecret,
	}
	log.Printf("Server started")

	router := gin.Default()
	router.POST("/api/auth", api.ApiAuthPost)
	router.Use(api.AuthMiddleware())
	{
		router.GET("/api/info", api.ApiInfoGet)
		router.GET("/api/buy/:item", api.ApiBuyItemGet)
		router.POST("/api/sendCoin", api.ApiSendCoinPost)
	}
	log.Fatal(router.Run(":8080"))
}
