/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /api/auth
// Аутентификация и получение JWT-токена. При первой аутентификации пользователь создается автоматически. 
func (api *DefaultAPI) ApiAuthPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/buy/:item
// Купить предмет за монеты. 
func (api *DefaultAPI) ApiBuyItemGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/info
// Получить информацию о монетах, инвентаре и истории транзакций. 
func (api *DefaultAPI) ApiInfoGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/sendCoin
// Отправить монеты другому пользователю. 
func (api *DefaultAPI) ApiSendCoinPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

