/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InfoResponseCoinHistoryReceivedInner struct {

	// Имя пользователя, который отправил монеты.
	FromUser string `json:"fromUser,omitempty" gorm:"column:from_user"`

	// Количество полученных монет.
	Amount int32 `json:"amount,omitempty"`
}
