/*
 * API Avito shop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "github.com/olgasinepalnikova/avito-task-2025-winter/server/go"
	"github.com/olgasinepalnikova/avito-task-2025-winter/server/go/database"
	"log"
)

func main() {
	database.Connect()

	routes := sw.ApiHandleFunctions{}
	log.Printf("Server started")

	router := sw.NewRouter(routes)
	log.Fatal(router.Run(":8080"))
}
